; BATTLE, AKG format, v1.0.

; Generated by Arkos Tracker 2.

BATTLE_Start
BATTLE_StartDisarkGenerateExternalLabel

BATTLE_DisarkByteRegionStart0
	db "AT20"
BATTLE_DisarkPointerRegionStart1
	dw BATTLE_ArpeggioTable	; The address of the Arpeggio table.
	dw BATTLE_PitchTable	; The address of the Pitch table.
	dw BATTLE_InstrumentTable	; The address of the Instrument table.
	dw BATTLE_EffectBlockTable	; The address of the Effect Block table.
BATTLE_DisarkPointerRegionEnd1


; The addresses of each Subsong:
BATTLE_DisarkPointerRegionStart2
	dw BATTLE_Subsong0_Start
BATTLE_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
BATTLE_ArpeggioTable
BATTLE_DisarkPointerRegionStart3
BATTLE_DisarkPointerRegionEnd3

; Declares all the Pitches.
BATTLE_PitchTable
BATTLE_DisarkPointerRegionStart4
BATTLE_DisarkPointerRegionEnd4

; Declares all the Instruments.
BATTLE_InstrumentTable
BATTLE_DisarkPointerRegionStart5
	dw BATTLE_EmptyInstrument
	dw BATTLE_Instrument1
	dw BATTLE_Instrument2
	dw BATTLE_Instrument3
	dw BATTLE_Instrument4
	dw BATTLE_Instrument5
BATTLE_DisarkPointerRegionEnd5

BATTLE_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
BATTLE_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

BATTLE_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

BATTLE_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 6	; Loop to silence.

BATTLE_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

BATTLE_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

BATTLE_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 550	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 650	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 700	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 750	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 800	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 850	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 900	; Pitch.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
BATTLE_EffectBlockTable

BATTLE_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
BATTLE_Subsong0_DisarkByteRegionStart0
BATTLE_Subsong0_Start
	db 1	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 2	; End index (>=0).
	db 3	; Initial speed (>=0).
	db 0	; Base note index (>=0).

BATTLE_Subsong0_Linker
BATTLE_Subsong0_DisarkPointerRegionStart1
; Position 0
BATTLE_Subsong0_Linker_Loop
	dw BATTLE_Subsong0_Track0
	dw BATTLE_Subsong0_Track1
	dw BATTLE_Subsong0_Track2
	dw BATTLE_Subsong0_LinkerBlock0

; Position 1
	dw BATTLE_Subsong0_Track3
	dw BATTLE_Subsong0_Track1
	dw BATTLE_Subsong0_Track2
	dw BATTLE_Subsong0_LinkerBlock0

; Position 2
	dw BATTLE_Subsong0_Track4
	dw BATTLE_Subsong0_Track1
	dw BATTLE_Subsong0_Track5
	dw BATTLE_Subsong0_LinkerBlock0

BATTLE_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
BATTLE_Subsong0_DisarkWordForceReference2
	dw BATTLE_Subsong0_Linker_Loop

BATTLE_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
BATTLE_Subsong0_DisarkWordForceReference3
	dw BATTLE_Subsong0_SpeedTrack0	; SpeedTrack address.
BATTLE_Subsong0_DisarkWordForceReference4
	dw BATTLE_Subsong0_EventTrack0	; EventTrack address.

BATTLE_Subsong0_Track0
	db 61, 31	; Waits for 32 lines.

	db 182
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track1
	db 175
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track2
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track3
	db 182
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track4
	db 182
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track5
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 48
	db 176
	db 3	; New Instrument (3).
	db 176
	db 4	; New Instrument (4).
	db 48
	db 48
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 176
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 176
	db 2	; New Instrument (2).
	db 176
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
BATTLE_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
BATTLE_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

BATTLE_Subsong0_DisarkByteRegionEnd0
