; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

BATTLE_Start
BATTLE_StartDisarkGenerateExternalLabel

BATTLE_DisarkByteRegionStart0
	db "AT20"
BATTLE_DisarkPointerRegionStart1
	dw BATTLE_ArpeggioTable	; The address of the Arpeggio table.
	dw BATTLE_PitchTable	; The address of the Pitch table.
	dw BATTLE_InstrumentTable	; The address of the Instrument table.
	dw BATTLE_EffectBlockTable	; The address of the Effect Block table.
BATTLE_DisarkPointerRegionEnd1


; The addresses of each Subsong:
BATTLE_DisarkPointerRegionStart2
	dw BATTLE_Subsong0_Start
BATTLE_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
BATTLE_ArpeggioTable
BATTLE_DisarkPointerRegionStart3
BATTLE_DisarkPointerRegionEnd3

; Declares all the Pitches.
BATTLE_PitchTable
BATTLE_DisarkPointerRegionStart4
BATTLE_DisarkPointerRegionEnd4

; Declares all the Instruments.
BATTLE_InstrumentTable
BATTLE_DisarkPointerRegionStart5
	dw BATTLE_EmptyInstrument
	dw BATTLE_Instrument1
	dw BATTLE_Instrument2
	dw BATTLE_Instrument3
	dw BATTLE_Instrument4
	dw BATTLE_Instrument5
	dw BATTLE_Instrument6
	dw BATTLE_Instrument7
BATTLE_DisarkPointerRegionEnd5

BATTLE_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
BATTLE_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

BATTLE_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

BATTLE_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

BATTLE_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 6	; Loop to silence.

BATTLE_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

BATTLE_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 50	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 100	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 200	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 250	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 350	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 6	; Loop to silence.

BATTLE_Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 200	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 250	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 350	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 450	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 550	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 6	; Loop to silence.

BATTLE_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 550	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 650	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 700	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 750	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 800	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 850	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 900	; Pitch.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
BATTLE_EffectBlockTable
BATTLE_DisarkPointerRegionStart6
	dw BATTLE_EffectBlock_P4P2	; Index 0
	dw BATTLE_EffectBlock_P4P3	; Index 1
	dw BATTLE_EffectBlock_P4P0	; Index 2
	dw BATTLE_EffectBlock_P4P1	; Index 3
BATTLE_DisarkPointerRegionEnd6

BATTLE_EffectBlock_P4P0
	db 4, 0
BATTLE_EffectBlock_P4P1
	db 4, 1
BATTLE_EffectBlock_P4P2
	db 4, 2
BATTLE_EffectBlock_P4P3
	db 4, 3

BATTLE_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
BATTLE_Subsong0_DisarkByteRegionStart0
BATTLE_Subsong0_Start
	db 1	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 20	; End index (>=0).
	db 3	; Initial speed (>=0).
	db 26	; Base note index (>=0).

BATTLE_Subsong0_Linker
BATTLE_Subsong0_DisarkPointerRegionStart1
; Position 0
BATTLE_Subsong0_Linker_Loop
	dw BATTLE_Subsong0_Track0
	dw BATTLE_Subsong0_Track1
	dw BATTLE_Subsong0_Track2
	dw BATTLE_Subsong0_LinkerBlock0

; Position 1
	dw BATTLE_Subsong0_Track17
	dw BATTLE_Subsong0_Track3
	dw BATTLE_Subsong0_Track4
	dw BATTLE_Subsong0_LinkerBlock1

; Position 2
	dw BATTLE_Subsong0_Track5
	dw BATTLE_Subsong0_Track6
	dw BATTLE_Subsong0_Track7
	dw BATTLE_Subsong0_LinkerBlock1

; Position 3
	dw BATTLE_Subsong0_Track8
	dw BATTLE_Subsong0_Track9
	dw BATTLE_Subsong0_Track10
	dw BATTLE_Subsong0_LinkerBlock1

; Position 4
	dw BATTLE_Subsong0_Track11
	dw BATTLE_Subsong0_Track12
	dw BATTLE_Subsong0_Track13
	dw BATTLE_Subsong0_LinkerBlock1

; Position 5
	dw BATTLE_Subsong0_Track14
	dw BATTLE_Subsong0_Track15
	dw BATTLE_Subsong0_Track16
	dw BATTLE_Subsong0_LinkerBlock2

; Position 6
	dw BATTLE_Subsong0_Track17
	dw BATTLE_Subsong0_Track3
	dw BATTLE_Subsong0_Track4
	dw BATTLE_Subsong0_LinkerBlock1

; Position 7
	dw BATTLE_Subsong0_Track5
	dw BATTLE_Subsong0_Track6
	dw BATTLE_Subsong0_Track7
	dw BATTLE_Subsong0_LinkerBlock1

; Position 8
	dw BATTLE_Subsong0_Track8
	dw BATTLE_Subsong0_Track9
	dw BATTLE_Subsong0_Track10
	dw BATTLE_Subsong0_LinkerBlock1

; Position 9
	dw BATTLE_Subsong0_Track11
	dw BATTLE_Subsong0_Track12
	dw BATTLE_Subsong0_Track13
	dw BATTLE_Subsong0_LinkerBlock1

; Position 10
	dw BATTLE_Subsong0_Track14
	dw BATTLE_Subsong0_Track15
	dw BATTLE_Subsong0_Track16
	dw BATTLE_Subsong0_LinkerBlock2

; Position 11
	dw BATTLE_Subsong0_Track17
	dw BATTLE_Subsong0_Track3
	dw BATTLE_Subsong0_Track4
	dw BATTLE_Subsong0_LinkerBlock1

; Position 12
	dw BATTLE_Subsong0_Track5
	dw BATTLE_Subsong0_Track6
	dw BATTLE_Subsong0_Track7
	dw BATTLE_Subsong0_LinkerBlock1

; Position 13
	dw BATTLE_Subsong0_Track8
	dw BATTLE_Subsong0_Track9
	dw BATTLE_Subsong0_Track10
	dw BATTLE_Subsong0_LinkerBlock1

; Position 14
	dw BATTLE_Subsong0_Track11
	dw BATTLE_Subsong0_Track12
	dw BATTLE_Subsong0_Track13
	dw BATTLE_Subsong0_LinkerBlock1

; Position 15
	dw BATTLE_Subsong0_Track14
	dw BATTLE_Subsong0_Track15
	dw BATTLE_Subsong0_Track16
	dw BATTLE_Subsong0_LinkerBlock2

; Position 16
	dw BATTLE_Subsong0_Track17
	dw BATTLE_Subsong0_Track3
	dw BATTLE_Subsong0_Track4
	dw BATTLE_Subsong0_LinkerBlock1

; Position 17
	dw BATTLE_Subsong0_Track5
	dw BATTLE_Subsong0_Track6
	dw BATTLE_Subsong0_Track7
	dw BATTLE_Subsong0_LinkerBlock1

; Position 18
	dw BATTLE_Subsong0_Track8
	dw BATTLE_Subsong0_Track9
	dw BATTLE_Subsong0_Track10
	dw BATTLE_Subsong0_LinkerBlock1

; Position 19
	dw BATTLE_Subsong0_Track11
	dw BATTLE_Subsong0_Track12
	dw BATTLE_Subsong0_Track13
	dw BATTLE_Subsong0_LinkerBlock1

; Position 20
	dw BATTLE_Subsong0_Track18
	dw BATTLE_Subsong0_Track19
	dw BATTLE_Subsong0_Track20
	dw BATTLE_Subsong0_LinkerBlock1

BATTLE_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
BATTLE_Subsong0_DisarkWordForceReference2
	dw BATTLE_Subsong0_Linker_Loop

BATTLE_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
BATTLE_Subsong0_DisarkWordForceReference3
	dw BATTLE_Subsong0_SpeedTrack0	; SpeedTrack address.
BATTLE_Subsong0_DisarkWordForceReference4
	dw BATTLE_Subsong0_EventTrack0	; EventTrack address.
BATTLE_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
BATTLE_Subsong0_DisarkWordForceReference5
	dw BATTLE_Subsong0_SpeedTrack1	; SpeedTrack address.
BATTLE_Subsong0_DisarkWordForceReference6
	dw BATTLE_Subsong0_EventTrack0	; EventTrack address.
BATTLE_Subsong0_LinkerBlock2
	db 72	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
BATTLE_Subsong0_DisarkWordForceReference7
	dw BATTLE_Subsong0_SpeedTrack1	; SpeedTrack address.
BATTLE_Subsong0_DisarkWordForceReference8
	dw BATTLE_Subsong0_EventTrack0	; EventTrack address.

BATTLE_Subsong0_Track0
	db 61, 15	; Waits for 16 lines.

	db 221
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 33
	db 61, 6	; Waits for 7 lines.

	db 36
	db 61, 6	; Waits for 7 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track1
	db 61, 15	; Waits for 16 lines.

	db 206
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track2
	db 61, 15	; Waits for 16 lines.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 150
	db 5	; New Instrument (5).
	db 22
	db 22
	db 150
	db 6	; New Instrument (6).
	db 22
	db 22
	db 22
	db 150
	db 7	; New Instrument (7).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track3
	db 142
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track4
	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 150
	db 5	; New Instrument (5).
	db 22
	db 22
	db 150
	db 6	; New Instrument (6).
	db 22
	db 150
	db 7	; New Instrument (7).
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track5
	db 61, 15	; Waits for 16 lines.

	db 161
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 36
	db 61, 6	; Waits for 7 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track6
	db 138
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track7
	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track8
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 173
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 60	; Waits for 1 line.

	db 38
	db 41
	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 51
	db 60	; Waits for 1 line.

	db 39
	db 43
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track9
	db 206
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track10
	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 22
	db 22
	db 22
	db 150
	db 6	; New Instrument (6).
	db 22
	db 22
	db 22
	db 150
	db 7	; New Instrument (7).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 6	; New Instrument (6).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 6	; New Instrument (6).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track11
	db 179
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 60	; Waits for 1 line.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track12
	db 207
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 79
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 8
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 8
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 72
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track13
	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 22
	db 22
	db 22
	db 150
	db 6	; New Instrument (6).
	db 22
	db 22
	db 22
	db 150
	db 7	; New Instrument (7).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 6	; New Instrument (6).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 3	; New Instrument (3).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 6	; New Instrument (6).
	db 150
	db 5	; New Instrument (5).
	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 5	; New Instrument (5).
	db 22
	db 150
	db 6	; New Instrument (6).
	db 22
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track14
	db 168
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 61, 30	; Waits for 31 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track15
	db 201
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 10
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 78
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 78
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 76
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track16
	db 150
	db 7	; New Instrument (7).
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track17
	db 61, 11	; Waits for 12 lines.

	db 166
	db 1	; New Instrument (1).
	db 40
	db 41
	db 43
	db 45
	db 61, 30	; Waits for 31 lines.

	db 46
	db 53
	db 61, 9	; Waits for 10 lines.

	db 48
	db 55
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track18
	db 168
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track19
	db 201
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 10
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 74
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


BATTLE_Subsong0_Track20
	db 150
	db 7	; New Instrument (7).
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 214
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 214
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 150
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 150
	db 4	; New Instrument (4).
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 61, 127	; Waits for 128 lines.


; The speed tracks
BATTLE_Subsong0_SpeedTrack0
	db 6	; Value: 3.
	db 253	; Wait for 127 lines.
BATTLE_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
BATTLE_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

BATTLE_Subsong0_DisarkByteRegionEnd0
