; DUNGEON, AKG format, v1.0.

; Generated by Arkos Tracker 2.

DUNGEON_Start
DUNGEON_StartDisarkGenerateExternalLabel

DUNGEON_DisarkByteRegionStart0
	db "AT20"
DUNGEON_DisarkPointerRegionStart1
	dw DUNGEON_ArpeggioTable	; The address of the Arpeggio table.
	dw DUNGEON_PitchTable	; The address of the Pitch table.
	dw DUNGEON_InstrumentTable	; The address of the Instrument table.
	dw DUNGEON_EffectBlockTable	; The address of the Effect Block table.
DUNGEON_DisarkPointerRegionEnd1


; The addresses of each Subsong:
DUNGEON_DisarkPointerRegionStart2
	dw DUNGEON_Subsong0_Start
DUNGEON_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
DUNGEON_ArpeggioTable
DUNGEON_DisarkPointerRegionStart3
DUNGEON_DisarkPointerRegionEnd3

; Declares all the Pitches.
DUNGEON_PitchTable
DUNGEON_DisarkPointerRegionStart4
	dw DUNGEON_Pitch1
DUNGEON_DisarkPointerRegionEnd4

DUNGEON_Pitch1
	db 2	; The speed.

	dw 0
DUNGEON_Pitch1_GotoNextForLine0
DUNGEON_DisarkWordForceReference5
	dw DUNGEON_Pitch1_GotoNextForLine0 + 2
	dw 0
DUNGEON_Pitch1_GotoNextForLine1
DUNGEON_DisarkWordForceReference6
	dw DUNGEON_Pitch1_GotoNextForLine1 + 2
	dw 0
DUNGEON_Pitch1_GotoNextForLine2
DUNGEON_DisarkWordForceReference7
	dw DUNGEON_Pitch1_GotoNextForLine2 + 2
	dw -1
DUNGEON_Pitch1_GotoNextForLine3
DUNGEON_DisarkWordForceReference8
	dw DUNGEON_Pitch1_GotoNextForLine3 + 2
	dw -4
DUNGEON_Pitch1_GotoNextForLine4
DUNGEON_DisarkWordForceReference9
	dw DUNGEON_Pitch1_GotoNextForLine4 + 2
	dw 2
DUNGEON_DisarkWordForceReference10
	dw DUNGEON_Pitch1 + 4 * 2 + 1

; Declares all the Instruments.
DUNGEON_InstrumentTable
DUNGEON_DisarkPointerRegionStart11
	dw DUNGEON_EmptyInstrument
	dw DUNGEON_Instrument1
	dw DUNGEON_Instrument2
DUNGEON_DisarkPointerRegionEnd11

DUNGEON_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
DUNGEON_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

DUNGEON_Instrument1
	db 3	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

DUNGEON_Instrument2
	db 1	; The speed (>0, 0 for 256).
DUNGEON_Instrument2_Loop	db 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
DUNGEON_DisarkWordForceReference12
	dw DUNGEON_Instrument2_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
DUNGEON_EffectBlockTable
DUNGEON_DisarkPointerRegionStart13
	dw DUNGEON_EffectBlock_P3P2P10P0	; Index 0
	dw DUNGEON_EffectBlock_P5P2P10P0	; Index 1
DUNGEON_DisarkPointerRegionEnd13

DUNGEON_EffectBlock_P3P2P10P0
	db 3, 2, 10, 0
DUNGEON_EffectBlock_P5P2P10P0
	db 5, 2, 10, 0

DUNGEON_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
DUNGEON_Subsong0_DisarkByteRegionStart0
DUNGEON_Subsong0_Start
	db 1	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 3	; End index (>=0).
	db 8	; Initial speed (>=0).
	db 9	; Base note index (>=0).

DUNGEON_Subsong0_Linker
DUNGEON_Subsong0_DisarkPointerRegionStart1
; Position 0
DUNGEON_Subsong0_Linker_Loop
	dw DUNGEON_Subsong0_Track0
	dw DUNGEON_Subsong0_Track2
	dw DUNGEON_Subsong0_Track1
	dw DUNGEON_Subsong0_LinkerBlock0

; Position 1
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_LinkerBlock1

; Position 2
	dw DUNGEON_Subsong0_Track3
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_Track5
	dw DUNGEON_Subsong0_LinkerBlock0

; Position 3
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_Track4
	dw DUNGEON_Subsong0_LinkerBlock1

DUNGEON_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
DUNGEON_Subsong0_DisarkWordForceReference2
	dw DUNGEON_Subsong0_Linker_Loop

DUNGEON_Subsong0_LinkerBlock0
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
DUNGEON_Subsong0_DisarkWordForceReference3
	dw DUNGEON_Subsong0_SpeedTrack0	; SpeedTrack address.
DUNGEON_Subsong0_DisarkWordForceReference4
	dw DUNGEON_Subsong0_EventTrack0	; EventTrack address.
DUNGEON_Subsong0_LinkerBlock1
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
DUNGEON_Subsong0_DisarkWordForceReference5
	dw DUNGEON_Subsong0_SpeedTrack0	; SpeedTrack address.
DUNGEON_Subsong0_DisarkWordForceReference6
	dw DUNGEON_Subsong0_EventTrack0	; EventTrack address.

DUNGEON_Subsong0_Track0
	db 242
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 51
	db 61, 6	; Waits for 7 lines.

	db 41
	db 61, 6	; Waits for 7 lines.

	db 53
	db 61, 127	; Waits for 128 lines.


DUNGEON_Subsong0_Track1
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 46
	db 61, 6	; Waits for 7 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


DUNGEON_Subsong0_Track2
	db 142
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


DUNGEON_Subsong0_Track3
	db 242
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 7	; Waits for 8 lines.

	db 44
	db 61, 8	; Waits for 9 lines.

	db 43
	db 61, 7	; Waits for 8 lines.

	db 41
	db 61, 127	; Waits for 128 lines.


DUNGEON_Subsong0_Track4
	db 61, 127	; Waits for 128 lines.


DUNGEON_Subsong0_Track5
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 179
	db 1	; New Instrument (1).
	db 61, 7	; Waits for 8 lines.

	db 55
	db 61, 7	; Waits for 8 lines.

	db 46
	db 61, 127	; Waits for 128 lines.


; The speed tracks
DUNGEON_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
DUNGEON_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

DUNGEON_Subsong0_DisarkByteRegionEnd0
