; Sarkboteur, AKG format, v1.0.

; Generated by Arkos Tracker 2.

castle_Start
castle_StartDisarkGenerateExternalLabel

castle_DisarkByteRegionStart0
	db "AT20"
castle_DisarkPointerRegionStart1
	dw castle_ArpeggioTable	; The address of the Arpeggio table.
	dw castle_PitchTable	; The address of the Pitch table.
	dw castle_InstrumentTable	; The address of the Instrument table.
	dw castle_EffectBlockTable	; The address of the Effect Block table.
castle_DisarkPointerRegionEnd1


; The addresses of each Subsong:
castle_DisarkPointerRegionStart2
	dw castle_Subsong0_Start
castle_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
castle_ArpeggioTable
castle_DisarkPointerRegionStart3
	dw castle_Arpeggio1
	dw castle_Arpeggio2
	dw castle_Arpeggio3
	dw castle_Arpeggio4
	dw castle_Arpeggio5
	dw castle_Arpeggio6
	dw castle_Arpeggio7
castle_DisarkPointerRegionEnd3

castle_Arpeggio1
	db 1	; The speed.

	db 0
	db 12
	db -128
castle_DisarkWordForceReference4
	dw castle_Arpeggio1 + 0 + 1	; Loop.

castle_Arpeggio2
	db 1	; The speed.

	db 12
	db 0
	db 12
	db 12
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 12
	db -128
castle_DisarkWordForceReference5
	dw castle_Arpeggio2 + 1 + 1	; Loop.

castle_Arpeggio3
	db 1	; The speed.

	db 1
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db -128
castle_DisarkWordForceReference6
	dw castle_Arpeggio3 + 0 + 1	; Loop.

castle_Arpeggio4
	db 1	; The speed.

	db 12
	db 0
	db 0
	db -128
castle_DisarkWordForceReference7
	dw castle_Arpeggio4 + 0 + 1	; Loop.

castle_Arpeggio5
	db 1	; The speed.

	db 0
	db 0
	db 0
	db 0
	db -5
	db -5
	db -5
	db -7
	db -7
	db -7
	db -11
	db -11
	db -11
	db -11
	db -7
	db -7
	db -7
	db -5
	db -5
	db -5
	db -128
castle_DisarkWordForceReference8
	dw castle_Arpeggio5 + 0 + 1	; Loop.

castle_Arpeggio6
	db 1	; The speed.

	db 0
	db 0
	db 0
	db 0
	db -4
	db -4
	db -4
	db -5
	db -5
	db -5
	db -11
	db -12
	db -12
	db -12
	db -5
	db -5
	db -5
	db -4
	db -4
	db -4
	db -128
castle_DisarkWordForceReference9
	dw castle_Arpeggio6 + 0 + 1	; Loop.

castle_Arpeggio7
	db 1	; The speed.

	db 0
	db 0
	db 0
	db 0
	db -2
	db -2
	db -2
	db -3
	db -3
	db -3
	db -6
	db -6
	db -6
	db -6
	db -3
	db -3
	db -3
	db -2
	db -2
	db -2
	db -128
castle_DisarkWordForceReference10
	dw castle_Arpeggio7 + 0 + 1	; Loop.

; Declares all the Pitches.
castle_PitchTable
castle_DisarkPointerRegionStart11
	dw castle_Pitch1
	dw castle_Pitch2
	dw castle_Pitch3
castle_DisarkPointerRegionEnd11

castle_Pitch1
	db 1	; The speed.

	dw -2
castle_DisarkWordForceReference12
	dw $ + 2
	dw 0
castle_DisarkWordForceReference13
	dw $ + 2
	dw 0
castle_DisarkWordForceReference14
	dw $ + 2
	dw -1
castle_DisarkWordForceReference15
	dw $ + 2
	dw -2
castle_DisarkWordForceReference16
	dw $ + 2
	dw -3
castle_DisarkWordForceReference17
	dw $ + 2
	dw -2
castle_DisarkWordForceReference18
	dw $ + 2
	dw -1
castle_DisarkWordForceReference19
	dw castle_Pitch1 + 4 * 2 + 1

castle_Pitch2
	db 1	; The speed.

	dw 0
castle_DisarkWordForceReference20
	dw $ + 2
	dw 0
castle_DisarkWordForceReference21
	dw $ + 2
	dw 0
castle_DisarkWordForceReference22
	dw $ + 2
	dw 0
castle_DisarkWordForceReference23
	dw $ + 2
	dw -1
castle_DisarkWordForceReference24
	dw $ + 2
	dw -2
castle_DisarkWordForceReference25
	dw $ + 2
	dw -2
castle_DisarkWordForceReference26
	dw $ + 2
	dw -1
castle_DisarkWordForceReference27
	dw castle_Pitch2 + 4 * 2 + 1

castle_Pitch3
	db 2	; The speed.

	dw 0
castle_DisarkWordForceReference28
	dw $ + 2
	dw -1
castle_DisarkWordForceReference29
	dw $ + 2
	dw 0
castle_DisarkWordForceReference30
	dw $ + 2
	dw 1
castle_DisarkWordForceReference31
	dw castle_Pitch3 + 4 * 0 + 1

; Declares all the Instruments.
castle_InstrumentTable
castle_DisarkPointerRegionStart32
	dw castle_EmptyInstrument
	dw castle_Instrument1
	dw castle_Instrument2
	dw castle_Instrument3
	dw castle_Instrument4
	dw castle_Instrument5
	dw castle_Instrument6
	dw castle_Instrument7
	dw castle_Instrument8
	dw castle_Instrument9
	dw castle_Instrument10
castle_DisarkPointerRegionEnd32

castle_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
castle_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

castle_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 130	; Simple case. Ratio: 5

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 130	; Simple case. Ratio: 5

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

castle_Instrument2
	db 1	; The speed (>0, 0 for 256).
castle_Instrument2_Loop	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference33
	dw castle_Instrument2_Loop	; Loop here.

castle_Instrument3
	db 2	; The speed (>0, 0 for 256).
	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

castle_Instrument3_Loop	db 201	; Soft only. Volume: 9. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference34
	dw castle_Instrument3_Loop	; Loop here.

castle_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 97	; Soft only. Volume: 12.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

castle_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 97	; Soft only. Volume: 12.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 132	; Simple case. Ratio: 3

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 132	; Simple case. Ratio: 3

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

castle_Instrument6
	db 3	; The speed (>0, 0 for 256).
	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

castle_Instrument6_Loop	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference35
	dw castle_Instrument6_Loop	; Loop here.

castle_Instrument7
	db 1	; The speed (>0, 0 for 256).
castle_Instrument7_Loop	db 4	; Hard to Soft. Envelope: 8. Retrig ? false. Noise ? false.
	db 10	; Complex case. Ratio: 5
	dw -4	; Destination pitch shift.

	db 7	; Loop.
castle_DisarkWordForceReference36
	dw castle_Instrument7_Loop	; Loop here.

castle_Instrument8
	db 1	; The speed (>0, 0 for 256).
castle_Instrument8_Loop	db 233	; Soft only. Volume: 13. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference37
	dw castle_Instrument8_Loop	; Loop here.

castle_Instrument9
	db 1	; The speed (>0, 0 for 256).
	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

castle_Instrument9_Loop	db 185	; Soft only. Volume: 7. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference38
	dw castle_Instrument9_Loop	; Loop here.

castle_Instrument10
	db 1	; The speed (>0, 0 for 256).
castle_Instrument10_Loop	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 7	; Loop.
castle_DisarkWordForceReference39
	dw castle_Instrument10_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
castle_EffectBlockTable
castle_DisarkPointerRegionStart40
	dw castle_EffectBlock_P11P1P6P1	; Index 0
	dw castle_EffectBlock_P1P6P3	; Index 1
	dw castle_EffectBlock_P14P16P0	; Index 2
	dw castle_EffectBlock_P5P0P11P0P6P1	; Index 3
	dw castle_EffectBlock_P5P0P11P1P6P1	; Index 4
	dw castle_EffectBlock_P10P2	; Index 5
	dw castle_EffectBlock_P5P1P13P6P5	; Index 6
	dw castle_EffectBlock_P1P11P0P6P2	; Index 7
	dw castle_EffectBlock_P11P1P6P0	; Index 8
	dw castle_EffectBlock_P5P1P6P4	; Index 9
	dw castle_EffectBlock_P5P1P6P6	; Index 10
	dw castle_EffectBlock_P16	; Index 11
	dw castle_EffectBlock_P20P0P5	; Index 12
	dw castle_EffectBlock_P4P4	; Index 13
castle_DisarkPointerRegionEnd40

castle_EffectBlock_P16
	db 16
castle_EffectBlock_P4P4
	db 4, 4
castle_EffectBlock_P14P16P0
	db 14, 16, 0
castle_EffectBlock_P11P1P6P0
	db 11, 1, 6, 0
castle_EffectBlock_P11P1P6P1
	db 11, 1, 6, 1
castle_EffectBlock_P5P1P13P6P5
	db 5, 1, 13, 6, 5
castle_EffectBlock_P1P11P0P6P2
	db 1, 11, 0, 6, 2
castle_EffectBlock_P5P1P6P4
	db 5, 1, 6, 4
castle_EffectBlock_P5P1P6P6
	db 5, 1, 6, 6
castle_EffectBlock_P5P0P11P0P6P1
	db 5, 0, 11, 0, 6, 1
castle_EffectBlock_P20P0P5
	db 20, 0, 5
castle_EffectBlock_P5P0P11P1P6P1
	db 5, 0, 11, 1, 6, 1
castle_EffectBlock_P10P2
	db 10, 2
castle_EffectBlock_P1P6P3
	db 1, 6, 3

castle_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
castle_Subsong0_DisarkByteRegionStart0
castle_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 79	; End index (>=0).
	db 5	; Initial speed (>=0).
	db 21	; Base note index (>=0).

castle_Subsong0_Linker
castle_Subsong0_DisarkPointerRegionStart1
; Position 0
castle_Subsong0_Linker_Loop
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track44
	dw castle_Subsong0_LinkerBlock0

; Position 1
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock0

; Position 2
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock0

; Position 3
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock0

; Position 4
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track4
	dw castle_Subsong0_LinkerBlock0

; Position 5
	dw castle_Subsong0_Track6
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track5
	dw castle_Subsong0_LinkerBlock1

; Position 6
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track8
	dw castle_Subsong0_LinkerBlock2

; Position 7
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track9
	dw castle_Subsong0_LinkerBlock3

; Position 8
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track10
	dw castle_Subsong0_LinkerBlock4

; Position 9
	dw castle_Subsong0_Track12
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track11
	dw castle_Subsong0_LinkerBlock5

; Position 10
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track4
	dw castle_Subsong0_LinkerBlock0

; Position 11
	dw castle_Subsong0_Track6
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track5
	dw castle_Subsong0_LinkerBlock1

; Position 12
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track8
	dw castle_Subsong0_LinkerBlock2

; Position 13
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track9
	dw castle_Subsong0_LinkerBlock3

; Position 14
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track13
	dw castle_Subsong0_LinkerBlock6

; Position 15
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track14
	dw castle_Subsong0_LinkerBlock7

; Position 16
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock8

; Position 17
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock9

; Position 18
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock10

; Position 19
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock11

; Position 20
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock12

; Position 21
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock13

; Position 22
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock14

; Position 23
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock5

; Position 24
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track16
	dw castle_Subsong0_LinkerBlock8

; Position 25
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track17
	dw castle_Subsong0_LinkerBlock15

; Position 26
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track18
	dw castle_Subsong0_LinkerBlock8

; Position 27
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock16

; Position 28
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track16
	dw castle_Subsong0_LinkerBlock8

; Position 29
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track17
	dw castle_Subsong0_LinkerBlock15

; Position 30
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track19
	dw castle_Subsong0_LinkerBlock6

; Position 31
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track15
	dw castle_Subsong0_LinkerBlock17

; Position 32
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track22
	dw castle_Subsong0_LinkerBlock18

; Position 33
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track23
	dw castle_Subsong0_LinkerBlock19

; Position 34
	dw castle_Subsong0_Track24
	dw castle_Subsong0_Track25
	dw castle_Subsong0_Track26
	dw castle_Subsong0_LinkerBlock18

; Position 35
	dw castle_Subsong0_Track27
	dw castle_Subsong0_Track28
	dw castle_Subsong0_Track29
	dw castle_Subsong0_LinkerBlock18

; Position 36
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track30
	dw castle_Subsong0_LinkerBlock20

; Position 37
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track30
	dw castle_Subsong0_LinkerBlock21

; Position 38
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track31
	dw castle_Subsong0_LinkerBlock22

; Position 39
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track31
	dw castle_Subsong0_LinkerBlock23

; Position 40
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track32
	dw castle_Subsong0_LinkerBlock4

; Position 41
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track32
	dw castle_Subsong0_LinkerBlock24

; Position 42
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track33
	dw castle_Subsong0_LinkerBlock25

; Position 43
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track33
	dw castle_Subsong0_LinkerBlock5

; Position 44
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track30
	dw castle_Subsong0_LinkerBlock20

; Position 45
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track30
	dw castle_Subsong0_LinkerBlock21

; Position 46
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track31
	dw castle_Subsong0_LinkerBlock22

; Position 47
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track31
	dw castle_Subsong0_LinkerBlock23

; Position 48
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track32
	dw castle_Subsong0_LinkerBlock4

; Position 49
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track32
	dw castle_Subsong0_LinkerBlock24

; Position 50
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track33
	dw castle_Subsong0_LinkerBlock25

; Position 51
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track33
	dw castle_Subsong0_LinkerBlock5

; Position 52
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track34
	dw castle_Subsong0_LinkerBlock26

; Position 53
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track34
	dw castle_Subsong0_LinkerBlock27

; Position 54
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track35
	dw castle_Subsong0_LinkerBlock22

; Position 55
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track35
	dw castle_Subsong0_LinkerBlock23

; Position 56
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track37
	dw castle_Subsong0_LinkerBlock28

; Position 57
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock28

; Position 58
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock29

; Position 59
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock30

; Position 60
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track37
	dw castle_Subsong0_LinkerBlock28

; Position 61
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock28

; Position 62
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track38
	dw castle_Subsong0_LinkerBlock31

; Position 63
	dw castle_Subsong0_Track20
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock31

; Position 64
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track36
	dw castle_Subsong0_LinkerBlock20

; Position 65
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track39
	dw castle_Subsong0_LinkerBlock21

; Position 66
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock20

; Position 67
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock21

; Position 68
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track36
	dw castle_Subsong0_LinkerBlock32

; Position 69
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track39
	dw castle_Subsong0_LinkerBlock33

; Position 70
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock32

; Position 71
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock34

; Position 72
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track36
	dw castle_Subsong0_LinkerBlock35

; Position 73
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track39
	dw castle_Subsong0_LinkerBlock36

; Position 74
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track0
	dw castle_Subsong0_LinkerBlock35

; Position 75
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock37

; Position 76
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track40
	dw castle_Subsong0_LinkerBlock25

; Position 77
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track41
	dw castle_Subsong0_LinkerBlock5

; Position 78
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track42
	dw castle_Subsong0_LinkerBlock25

; Position 79
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track43
	dw castle_Subsong0_LinkerBlock5

castle_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
castle_Subsong0_DisarkWordForceReference2
	dw castle_Subsong0_Linker_Loop

castle_Subsong0_LinkerBlock0
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference3
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference4
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock1
	db 32	; Height.
	db 5	; Transposition 0.
	db 5	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference5
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference6
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock2
	db 16	; Height.
	db 0	; Transposition 0.
	db -4	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference7
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference8
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock3
	db 16	; Height.
	db -7	; Transposition 0.
	db 1	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference9
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference10
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock4
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference11
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference12
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock5
	db 16	; Height.
	db -1	; Transposition 0.
	db 7	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference13
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference14
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock6
	db 16	; Height.
	db -2	; Transposition 0.
	db 6	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference15
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference16
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock7
	db 16	; Height.
	db -9	; Transposition 0.
	db -1	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference17
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference18
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock8
	db 16	; Height.
	db -4	; Transposition 0.
	db 4	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference19
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference20
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock9
	db 16	; Height.
	db -4	; Transposition 0.
	db 4	; Transposition 1.
	db 5	; Transposition 2.
castle_Subsong0_DisarkWordForceReference21
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference22
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock10
	db 16	; Height.
	db -7	; Transposition 0.
	db 1	; Transposition 1.
	db 6	; Transposition 2.
castle_Subsong0_DisarkWordForceReference23
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference24
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock11
	db 16	; Height.
	db -7	; Transposition 0.
	db 1	; Transposition 1.
	db 6	; Transposition 2.
castle_Subsong0_DisarkWordForceReference25
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference26
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock12
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 6	; Transposition 2.
castle_Subsong0_DisarkWordForceReference27
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference28
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock13
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 11	; Transposition 2.
castle_Subsong0_DisarkWordForceReference29
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference30
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock14
	db 16	; Height.
	db -1	; Transposition 0.
	db 7	; Transposition 1.
	db 12	; Transposition 2.
castle_Subsong0_DisarkWordForceReference31
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference32
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock15
	db 16	; Height.
	db -5	; Transposition 0.
	db 3	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference33
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference34
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock16
	db 16	; Height.
	db -7	; Transposition 0.
	db 1	; Transposition 1.
	db 14	; Transposition 2.
castle_Subsong0_DisarkWordForceReference35
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference36
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock17
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 15	; Transposition 2.
castle_Subsong0_DisarkWordForceReference37
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference38
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock18
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference39
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference40
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock19
	db 48	; Height.
	db 2	; Transposition 0.
	db 2	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference41
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference42
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock20
	db 16	; Height.
	db -8	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference43
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference44
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock21
	db 16	; Height.
	db -8	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference45
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference46
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock22
	db 16	; Height.
	db -3	; Transposition 0.
	db 5	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference47
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference48
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock23
	db 16	; Height.
	db -3	; Transposition 0.
	db 5	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference49
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference50
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock24
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference51
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference52
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock25
	db 16	; Height.
	db -1	; Transposition 0.
	db 7	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference53
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference54
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock26
	db 16	; Height.
	db 0	; Transposition 0.
	db 8	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference55
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference56
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock27
	db 16	; Height.
	db 0	; Transposition 0.
	db 8	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference57
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference58
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock28
	db 16	; Height.
	db 8	; Transposition 0.
	db 8	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference59
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference60
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock29
	db 16	; Height.
	db 7	; Transposition 0.
	db 7	; Transposition 1.
	db 3	; Transposition 2.
castle_Subsong0_DisarkWordForceReference61
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference62
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock30
	db 16	; Height.
	db 7	; Transposition 0.
	db 7	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference63
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference64
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock31
	db 16	; Height.
	db 16	; Transposition 0.
	db 16	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference65
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference66
	dw castle_Subsong0_EventTrack2	; EventTrack address.
castle_Subsong0_LinkerBlock32
	db 16	; Height.
	db -3	; Transposition 0.
	db 5	; Transposition 1.
	db 5	; Transposition 2.
castle_Subsong0_DisarkWordForceReference67
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference68
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock33
	db 16	; Height.
	db -3	; Transposition 0.
	db 5	; Transposition 1.
	db 5	; Transposition 2.
castle_Subsong0_DisarkWordForceReference69
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference70
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock34
	db 16	; Height.
	db -3	; Transposition 0.
	db 5	; Transposition 1.
	db -2	; Transposition 2.
castle_Subsong0_DisarkWordForceReference71
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference72
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock35
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 3	; Transposition 2.
castle_Subsong0_DisarkWordForceReference73
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference74
	dw castle_Subsong0_EventTrack0	; EventTrack address.
castle_Subsong0_LinkerBlock36
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db 3	; Transposition 2.
castle_Subsong0_DisarkWordForceReference75
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference76
	dw castle_Subsong0_EventTrack1	; EventTrack address.
castle_Subsong0_LinkerBlock37
	db 16	; Height.
	db -10	; Transposition 0.
	db -2	; Transposition 1.
	db -4	; Transposition 2.
castle_Subsong0_DisarkWordForceReference77
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference78
	dw castle_Subsong0_EventTrack1	; EventTrack address.

castle_Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track1
	db 132
	db 1	; New Instrument (1).
	db 16
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 16
	db 28
	db 4
	db 60	; Waits for 1 line.

	db 16
	db 16
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 28
	db 4
	db 16
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 16
	db 28
	db 4
	db 60	; Waits for 1 line.

	db 16
	db 16
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 28
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track2
	db 255
	db 80	; Escape note (80).
	db 10	; New Instrument (10).
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track3
	db 208
	db 2	; New Instrument (2).
	db 13	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track4
	db 223
	db 3	; New Instrument (3).
	db 3	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 30
	db 28
	db 31
	db 61, 10	; Waits for 11 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track5
	db 225
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 30
	db 33
	db 61, 10	; Waits for 11 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track6
	db 132
	db 4	; New Instrument (4).
	db 16
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 16
	db 156
	db 5	; New Instrument (5).
	db 132
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 16
	db 16
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 156
	db 5	; New Instrument (5).
	db 132
	db 4	; New Instrument (4).
	db 16
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 16
	db 156
	db 5	; New Instrument (5).
	db 132
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 16
	db 16
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 156
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track7
	db 140
	db 4	; New Instrument (4).
	db 24
	db 12
	db 60	; Waits for 1 line.

	db 12
	db 24
	db 36
	db 12
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track8
	db 228
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track9
	db 225
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track10
	db 230
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track11
	db 227
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track12
	db 140
	db 4	; New Instrument (4).
	db 24
	db 12
	db 60	; Waits for 1 line.

	db 12
	db 24
	db 164
	db 5	; New Instrument (5).
	db 140
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 164
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track13
	db 230
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track14
	db 162
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track15
	db 155
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track16
	db 231
	db 3	; New Instrument (3).
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 36
	db 39
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 38
	db 39
	db 60	; Waits for 1 line.

	db 38
	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track17
	db 166
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 36
	db 35
	db 38
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track18
	db 167
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 38
	db 36
	db 39
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 38
	db 39
	db 60	; Waits for 1 line.

	db 38
	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track19
	db 166
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 36
	db 34
	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 39
	db 41
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track20
	db 247
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track21
	db 191
	db 16	; Escape note (16).
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track22
	db 223
	db 6	; New Instrument (6).
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 27
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 26
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track23
	db 166
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track24
	db 242
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 52
	db 61, 6	; Waits for 7 lines.

	db 53
	db 61, 6	; Waits for 7 lines.

	db 54
	db 61, 6	; Waits for 7 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track25
	db 130
	db 8	; New Instrument (8).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 13	; Escape note (13).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 14	; Escape note (14).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 15	; Escape note (15).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 16	; Escape note (16).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track26
	db 171
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track27
	db 255
	db 78	; Escape note (78).
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 63
	db 80	; Escape note (80).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 81	; Escape note (81).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 82	; Escape note (82).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 83	; Escape note (83).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 84	; Escape note (84).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track28
	db 191
	db 18	; Escape note (18).
	db 8	; New Instrument (8).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 20	; Escape note (20).
	db 61, 6	; Waits for 7 lines.

	db 0
	db 61, 6	; Waits for 7 lines.

	db 1
	db 61, 6	; Waits for 7 lines.

	db 2
	db 61, 6	; Waits for 7 lines.

	db 3
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track29
	db 178
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track30
	db 239
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 43
	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 40
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 43
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track31
	db 240
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 45
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 40
	db 50
	db 60	; Waits for 1 line.

	db 48
	db 47
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track32
	db 237
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 42
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 43
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track33
	db 239
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 45
	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 42
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 45
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track34
	db 240
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 46
	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 41
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 43
	db 40
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track35
	db 237
	db 9	; New Instrument (9).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 43
	db 42
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 38
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 40
	db 36
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track36
	db 232
	db 3	; New Instrument (3).
	db 4	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track37
	db 255
	db 83	; Escape note (83).
	db 10	; New Instrument (10).
	db 9	; Index to an effect block.
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track38
	db 255
	db 78	; Escape note (78).
	db 10	; New Instrument (10).
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track39
	db 164
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 35
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track40
	db 239
	db 6	; New Instrument (6).
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track41
	db 175
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track42
	db 175
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track43
	db 170
	db 6	; New Instrument (6).
	db 61, 10	; Waits for 11 lines.

	db 124	; No note, but effects.
	db 12	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track44
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
castle_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
castle_Subsong0_EventTrack0
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 3	; Wait for 2 lines.
	db 8	; Value: 4.
	db 3	; Wait for 2 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 1	; Wait for 1 lines.
	db 14	; Value: 7.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 14	; Value: 7.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 3	; Wait for 2 lines.
	db 8	; Value: 4.
	db 3	; Wait for 2 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 10	; Value: 5.
	db 191	; Wait for 96 lines.
castle_Subsong0_EventTrack1
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 14	; Value: 7.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 3	; Wait for 2 lines.
	db 8	; Value: 4.
	db 3	; Wait for 2 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 10	; Value: 5.
	db 223	; Wait for 112 lines.
castle_Subsong0_EventTrack2
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 5	; Wait for 3 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 14	; Value: 7.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 5	; Wait for 3 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 12	; Value: 6.
	db 1	; Wait for 1 lines.
	db 8	; Value: 4.
	db 1	; Wait for 1 lines.
	db 10	; Value: 5.
	db 165	; Wait for 83 lines.

castle_Subsong0_DisarkByteRegionEnd0
