; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

castle_Start
castle_StartDisarkGenerateExternalLabel

castle_DisarkByteRegionStart0
	db "AT20"
castle_DisarkPointerRegionStart1
	dw castle_ArpeggioTable	; The address of the Arpeggio table.
	dw castle_PitchTable	; The address of the Pitch table.
	dw castle_InstrumentTable	; The address of the Instrument table.
	dw castle_EffectBlockTable	; The address of the Effect Block table.
castle_DisarkPointerRegionEnd1


; The addresses of each Subsong:
castle_DisarkPointerRegionStart2
	dw castle_Subsong0_Start
castle_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
castle_ArpeggioTable
castle_DisarkPointerRegionStart3
castle_DisarkPointerRegionEnd3

; Declares all the Pitches.
castle_PitchTable
castle_DisarkPointerRegionStart4
castle_DisarkPointerRegionEnd4

; Declares all the Instruments.
castle_InstrumentTable
castle_DisarkPointerRegionStart5
	dw castle_EmptyInstrument
	dw castle_Instrument1
	dw castle_Instrument2
	dw castle_Instrument3
	dw castle_Instrument4
castle_DisarkPointerRegionEnd5

castle_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
castle_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

castle_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

castle_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

castle_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

castle_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
castle_EffectBlockTable
castle_DisarkPointerRegionStart6
	dw castle_EffectBlock_P4P1	; Index 0
	dw castle_EffectBlock_P4P2	; Index 1
	dw castle_EffectBlock_P4P3	; Index 2
	dw castle_EffectBlock_P4P0	; Index 3
castle_DisarkPointerRegionEnd6

castle_EffectBlock_P4P0
	db 4, 0
castle_EffectBlock_P4P1
	db 4, 1
castle_EffectBlock_P4P2
	db 4, 2
castle_EffectBlock_P4P3
	db 4, 3

castle_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
castle_Subsong0_DisarkByteRegionStart0
castle_Subsong0_Start
	db 1	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 10	; End index (>=0).
	db 3	; Initial speed (>=0).
	db 27	; Base note index (>=0).

castle_Subsong0_Linker
castle_Subsong0_DisarkPointerRegionStart1
; Position 0
castle_Subsong0_Linker_Loop
	dw castle_Subsong0_Track0
	dw castle_Subsong0_Track1
	dw castle_Subsong0_Track2
	dw castle_Subsong0_LinkerBlock0

; Position 1
	dw castle_Subsong0_Track3
	dw castle_Subsong0_Track4
	dw castle_Subsong0_Track5
	dw castle_Subsong0_LinkerBlock0

; Position 2
	dw castle_Subsong0_Track6
	dw castle_Subsong0_Track7
	dw castle_Subsong0_Track8
	dw castle_Subsong0_LinkerBlock0

; Position 3
	dw castle_Subsong0_Track9
	dw castle_Subsong0_Track10
	dw castle_Subsong0_Track11
	dw castle_Subsong0_LinkerBlock0

; Position 4
	dw castle_Subsong0_Track12
	dw castle_Subsong0_Track13
	dw castle_Subsong0_Track14
	dw castle_Subsong0_LinkerBlock0

; Position 5
	dw castle_Subsong0_Track15
	dw castle_Subsong0_Track16
	dw castle_Subsong0_Track17
	dw castle_Subsong0_LinkerBlock0

; Position 6
	dw castle_Subsong0_Track18
	dw castle_Subsong0_Track19
	dw castle_Subsong0_Track20
	dw castle_Subsong0_LinkerBlock0

; Position 7
	dw castle_Subsong0_Track21
	dw castle_Subsong0_Track22
	dw castle_Subsong0_Track23
	dw castle_Subsong0_LinkerBlock0

; Position 8
	dw castle_Subsong0_Track24
	dw castle_Subsong0_Track25
	dw castle_Subsong0_Track26
	dw castle_Subsong0_LinkerBlock0

; Position 9
	dw castle_Subsong0_Track27
	dw castle_Subsong0_Track28
	dw castle_Subsong0_Track29
	dw castle_Subsong0_LinkerBlock0

; Position 10
	dw castle_Subsong0_Track30
	dw castle_Subsong0_Track31
	dw castle_Subsong0_Track32
	dw castle_Subsong0_LinkerBlock0

castle_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
castle_Subsong0_DisarkWordForceReference2
	dw castle_Subsong0_Linker_Loop

castle_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
castle_Subsong0_DisarkWordForceReference3
	dw castle_Subsong0_SpeedTrack0	; SpeedTrack address.
castle_Subsong0_DisarkWordForceReference4
	dw castle_Subsong0_EventTrack0	; EventTrack address.

castle_Subsong0_Track0
	db 151
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 23
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 18
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 15
	db 60	; Waits for 1 line.

	db 18
	db 61, 6	; Waits for 7 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 18
	db 61, 6	; Waits for 7 lines.

	db 97
	db 3	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 80
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 97
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track1
	db 139
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 11
	db 11
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 2
	db 2
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 6
	db 1
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 4
	db 6
	db 60	; Waits for 1 line.

	db 8
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track2
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 21
	db 21
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 21
	db 21
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track3
	db 213
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 21
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 16
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 21
	db 60	; Waits for 1 line.

	db 25
	db 61, 6	; Waits for 7 lines.

	db 105
	db 3	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 101
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 49
	db 47
	db 45
	db 44
	db 45
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track4
	db 137
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 9
	db 4
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 13
	db 8
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track5
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 21
	db 149
	db 4	; New Instrument (4).
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track6
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 158
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 44
	db 109
	db 3	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 42
	db 40
	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 49
	db 47
	db 45
	db 44
	db 45
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track7
	db 139
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 13
	db 60	; Waits for 1 line.

	db 13
	db 13
	db 14
	db 60	; Waits for 1 line.

	db 14
	db 14
	db 14
	db 60	; Waits for 1 line.

	db 14
	db 14
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 8
	db 60	; Waits for 1 line.

	db 8
	db 8
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track8
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track9
	db 182
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 114
	db 3	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 54
	db 52
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 54
	db 52
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track10
	db 139
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 13
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 5
	db 4
	db 2
	db 0
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track11
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track12
	db 181
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 63
	db 84	; Escape note (84).
	db 55
	db 61, 6	; Waits for 7 lines.

	db 53
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 63
	db 84	; Escape note (84).
	db 55
	db 61, 6	; Waits for 7 lines.

	db 37
	db 61, 6	; Waits for 7 lines.

	db 35
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track13
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 13
	db 60	; Waits for 1 line.

	db 13
	db 13
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track14
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track15
	db 210
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 18
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 85
	db 3	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 89
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 61, 6	; Waits for 7 lines.

	db 23
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 18
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 15
	db 60	; Waits for 1 line.

	db 18
	db 61, 6	; Waits for 7 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track16
	db 134
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 6
	db 6
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 9
	db 4
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 11
	db 11
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 2
	db 2
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track17
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 21
	db 85
	db 2	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 21
	db 21
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track18
	db 146
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 97
	db 3	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 80
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 97
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 85
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 21
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 16
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 21
	db 60	; Waits for 1 line.

	db 25
	db 61, 6	; Waits for 7 lines.

	db 105
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track19
	db 134
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 6
	db 1
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 4
	db 6
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 9
	db 4
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 13
	db 8
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track20
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 21
	db 21
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 21
	db 149
	db 4	; New Instrument (4).
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 85
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track21
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 229
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 49
	db 47
	db 45
	db 44
	db 45
	db 61, 10	; Waits for 11 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 44
	db 109
	db 3	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 42
	db 40
	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track22
	db 134
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 13
	db 60	; Waits for 1 line.

	db 13
	db 13
	db 14
	db 60	; Waits for 1 line.

	db 14
	db 14
	db 14
	db 60	; Waits for 1 line.

	db 14
	db 14
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track23
	db 213
	db 3	; New Instrument (3).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track24
	db 158
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 49
	db 47
	db 45
	db 44
	db 45
	db 61, 6	; Waits for 7 lines.

	db 54
	db 61, 22	; Waits for 23 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track25
	db 134
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 6
	db 60	; Waits for 1 line.

	db 6
	db 6
	db 8
	db 60	; Waits for 1 line.

	db 8
	db 8
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 11
	db 60	; Waits for 1 line.

	db 11
	db 11
	db 13
	db 60	; Waits for 1 line.

	db 1
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track26
	db 213
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 149
	db 4	; New Instrument (4).
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track27
	db 242
	db 1	; New Instrument (1).
	db 3	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 54
	db 52
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 54
	db 52
	db 61, 6	; Waits for 7 lines.

	db 53
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 63
	db 84	; Escape note (84).
	db 55
	db 61, 6	; Waits for 7 lines.

	db 53
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 63
	db 84	; Escape note (84).
	db 55
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track28
	db 130
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 4
	db 60	; Waits for 1 line.

	db 4
	db 4
	db 5
	db 4
	db 2
	db 0
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 5
	db 60	; Waits for 1 line.

	db 5
	db 5
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track29
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track30
	db 165
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 35
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 37
	db 61, 6	; Waits for 7 lines.

	db 82
	db 0	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 18
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 85
	db 3	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 89
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track31
	db 137
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 9
	db 60	; Waits for 1 line.

	db 9
	db 9
	db 13
	db 60	; Waits for 1 line.

	db 13
	db 13
	db 1
	db 60	; Waits for 1 line.

	db 1
	db 1
	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 6
	db 6
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 9
	db 4
	db 60	; Waits for 1 line.

	db 9
	db 61, 127	; Waits for 128 lines.


castle_Subsong0_Track32
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 149
	db 3	; New Instrument (3).
	db 21
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 149
	db 3	; New Instrument (3).
	db 149
	db 4	; New Instrument (4).
	db 85
	db 2	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 149
	db 4	; New Instrument (4).
	db 21
	db 85
	db 2	; Index to an effect block.
	db 21
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 149
	db 3	; New Instrument (3).
	db 85
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 85
	db 1	; Index to an effect block.
	db 21
	db 213
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 21
	db 85
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
castle_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
castle_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

castle_Subsong0_DisarkByteRegionEnd0
